package streams;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;


public class CollectorsMethod {
	
	private static Collection<Integer> numbersWithoutDups;

	public static void main(String[] args) {
		
		List<Integer> numbers = Arrays.asList(10, 20, 30, 11, 20, 33, 4, 44, 55, 20);
		Set<Integer> numbersWithoutDups = numbers.stream().collect(Collectors.toSet()); 
		System.out.println("original list: " + numbers); 
		System.out.println("Set generated by Collectors: " + numbersWithoutDups);

		

	}


}
